### ISSUE TITLE
Image encoding issue

### ISSUE THREAD

**Issue by mzahana** [christianrauch/camera_ros#29]
Hi @christianrauch 

I noticed that published image has encodings that don't match any of the following
`16UC1 / mono16, 8UC1 / mono8, 8UC3 / rgb8 / bgr8, 8UC4 / bgra8, bayer_rggb8, bayer_bggr8, bayer_gbrg8, bayer_grbg8`

I tried to use [Kalibr](https://github.com/ethz-asl/kalibr) to calibrate my stereo camera, but it failed because the image topic has unsupported encoding. Here is the error I get
```sh
RuntimeError: Exception during multithreaded extraction: Unsupported Image Encoding: 'yuv422_yuy2'
```

Is it possible to map the encodings to the supported ones such as `16UC1 / mono16, 8UC1 / mono8, 8UC3 / rgb8 / bgr8, 8UC4 / bgra8, bayer_rggb8, bayer_bggr8, bayer_gbrg8, bayer_grbg8` ?

**Comment by christianrauch** [comment]
The supported image encodings are listed here:
https://github.com/christianrauch/camera_ros/blob/47eea6d63d21c3d179c377a87b87e7b5bb57d762/src/format_mapping.cpp#L16-L38

Since the node does not convert between pixel formats to avoid memory copies, the camera has to support the pixel format of the ROS message and vice versa.

If you want to use `yuv422_yuy2`, then your camera has to support `YUYV`. But if your camera supports `XRGB8888` (a.k.a. `XR24`) for example, you can use the ROS format `bgra8`.

If you need the message in a format that is not supported by the camera natively, you would have to convert from the camera to your target format.

**Comment by mzahana** [comment]
Thanks!
